# default: &default
#   adapter: sqlite3
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   timeout: 5000

# development:
#   <<: *default
#   database: db/development.sqlite3

# test:
#   <<: *default
#   database: db/test.sqlite3

# production:
#   <<: *default
#   database: db/production.sqlite3

# development:
#   adapter: sqlite3
#   database: db/development.sqlite3

# production:
#   adapter: postgresql
#   database: db/production.sqlite3


default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: "db/development.sqlite3"

test:
  <<: *default
  database: "db/test.sqlite3"

production:
  <<: *default
  database: d7j4ur1fsk1qjc
  username: chbqhnqgfrgeor
  host: ec2-52-4-87-74.compute-1.amazonaws.com
  password: 10e81b4d09e26a352b706152fc88e4a3dcd3be6b405b661f5ac374b9c339b335
